server:
    port: 8888
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: todo_db
    application:
        name: todo
logging:
  level:
    '[org.springframework.data.mongodb]': DEBUG